version: "3.8"

services:
  app:
    volumes:
      - .:/app
      - var:/app/var
    environment:
      APP_ENV: dev

      # Do not use this secret in production, only for testing!
      APP_SECRET: fd7061a91fb9b2754eb89c641203d138

volumes:
  var:
