unknown-title: "Unknown"
runtime: "{runtime} min"

error-page:
  400:
    title: "Bad Request"
    message: "Your browser sent an request which could not be understood!"
  404:
    title: "Page not found"
    message: "The requested page could not be found!"
  500:
    title: "Internal server error"
    message: "An internal server error occurred! Check server logs for details."

register:
  title: "Register new account"
  username: "Username"
  password: "Password"
  password-repeat: "Password (repeat)"
  submit: "Register"
  already-have-account: "Already have an account?"
  error:
    username-missing: "No username given"
    username-taken: "The username is already taken"
    password-missing: "No password given"
    passwords-do-not-match: "Passwords are not the same"
    not-enabled: "Registration is not enabled"

login:
  title: "Login"
  header: "Login to your account"
  username: "Username"
  password: "Password"
  remember-me: "Stay logged-in"
  submit: "Login"

user:
  profile: "Profile"
  history: "History"
  show-progress: "TV show progress"
  logout: "Logout"
  login: "Login"
  no-history-available: "No history available."

search:
  title: "Search"
  placeholder: "Search for shows, episodes and movies"
  no-results: "No results for query ''{query}''."

navbar:
  shows: "Shows"
  movies: "Movies"

shows:
  season: "Season {number}"
  episode: "Episode {number}"
  count:
    shows: >-
      {count, plural,
        =1    {1 show}
        other {# shows}
      }
    seasons: >-
      {count, plural,
        =1    {1 season}
        other {# seasons}
      }
    episodes: >-
      {count, plural,
        =1    {1 episode}
        other {# episodes}
      }
  all-shows: "All shows"
  seasons: "Seasons"
  episodes: "Episodes"
  latest-episodes: "Latest episodes"
  random-episodes: "Random episodes"
  latest-watched-episodes: "Latest watched episodes"
  most-watched-episodes: "Most watched episodes"
  least-watched-episodes: "Least watched episodes"
  unwatched-episodes: "Unwatched episodes"
  no-shows-available: "No shows available."
  no-seasons-available: "No seasons available."
  no-episodes-available: "No episodes available."
  add-new: "Add show"
  status:
    upcoming: "Upcoming"
    continuing: "Continuing"
    ended: "Ended"

movies:
  all-movies: "All movies"
  no-movies-available: "No movies available."
  add-new: "Add movie"
  count: >-
    {count, plural,
      =1    {1 movie}
      other {# movies}
    }
  latest-movies: "Latest movies"
  latest-watched-movies: "Latest watched movies"

views:
  views: >-
    {count, plural,
      =1    {1 view}
      other {# views}
    }
  add-view: "Add view"
  remove:
    header: "Remove history entries?"
    this-view: "This view"
    all-views: "All views"
    cancel: "Cancel"
  add:
    header: "Add view"
    datetime: "Date and time"
    now: "Now"
    ok: "OK"
    cancel: "Cancel"

library-management:
  title: "Administration"
  count: >-
    {count, plural,
      =1    {1 item}
      other {# items}
    }
  add-item: "Add item"
  delete-item: "Delete item"
  confirm: "Confirm"
  cancel: "Cancel"
  delete-item-failed: "Deleting item failed"
  no-items-available: "No items available."
  columns:
    title: "Title"
    type: "Type"
    options: "Options"
  types:
    movie: "Movie"
    show: "Show"
  add-items:
    page-title: "Add movies or shows"
    type-title: "Type"
    title: "Title of the movie or show"
    year: "Year (optional)"
    search: "Search"
    no-results: "Nothing found."
    in-library: "In library"
    add-to-library: "Add to library"
  errors:
    view-exists: "At least one view of this item exists. Remove all views of it and try again."