error-page:
  400:
    title: "Bad Request"
    message: "Your browser sent an request which could not be understood!"
  404:
    title: "Page not found"
    message: "The requested page could not be found!"

register:
  title: "Register new account"
  username: "Username"
  password: "Password"
  password-repeat: "Password (repeat)"
  submit: "Register"
  already-have-account: "Already have an account?"
  error:
    username-missing: "No username given"
    username-taken: "The username is already taken"
    password-missing: "No password given"
    passwords-do-not-match: "Passwords are not the same"

login:
  title: "Login"
  header: "Login to your account"
  username: "Username"
  password: "Password"
  remember-me: "Remember me"
  submit: "Login"

user:
  profile: "Profile"
  history: "History"
  show-progress: "TV show progress"
  logout: "Logout"
  login: "Login"
  latest-watched-episodes: "Latest watched episodes"
  latest-watched-movies: "Latest watched movies"
  no-history-available: "No history available."

search:
  title: "Search"
  placeholder: "Search for shows, episodes and movies"
  no-results: "No results for query '{query}'."

overview:
  shows: "Shows"
  movies: "Movies"
  latest-episodes: "Latest episodes"
  latest-movies: "Latest movies"

shows:
  season: "Season {number}"
  episode: "Episode {number}"
  episode-count: "{count} episodes"
  all-shows: "All shows"
  seasons: "Seasons"
  episodes: "Episodes"
  no-shows-available: "No shows available."
  no-seasons-available: "No seasons available."
  no-episodes-available: "No episodes available."

movies:
  all-movies: "All movies"
  no-movies-available: "No movies available."

views:
  views: "{count} plays"
  add-view: "Add view"
  remove:
    header: "Remove history entries?"
    this-view: "This view"
    all-views: "All views"
    cancel: "Cancel"