imports:
  - resource: "defaults.yaml"
  - resource: "config.yaml"
    ignore_errors: not_found

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  tracky\:
    resource: '../src/main/php/tracky'
    exclude:
      - '../src/main/php/tracky/DependencyInjection/'
      - '../src/main/php/tracky/Entity/'
      - '../src/main/php/tracky/Kernel.php'

  tracky\console\FetchDataCommand:
    arguments:
      $downloadAllImages: "%image-fetcher.download-all-on-update%"
  tracky\console\UpdateDataCommand:
    arguments:
      $showFetchInterval: "%show-fetch-interval%"
      $downloadAllImages: "%image-fetcher.download-all-on-update%"
  tracky\controller\HistoryController:
    arguments:
      $itemsPerPage: "%history.items-per-page%"
      $maxPreviousNextPages: "%history.max-previous-next-pages%"
  tracky\controller\HomeController:
    arguments:
      $maxEpisodes: "%overview.max-episodes%"
      $maxMovies: "%overview.max-movies%"
      $maxNextEpisodeShows: "%overview.max-next-episode-shows%"
  tracky\controller\ShowController:
    arguments:
      $maxEpisodes: "%shows.max-episodes%"
  tracky\controller\UserController:
    arguments:
      $enableRegister: "%user.enable-register%"
  tracky\dataprovider\Helper:
    arguments:
      $movieProvider: "%data-provider.movies%"
      $showProvider: "%data-provider.shows%"
  tracky\dataprovider\TMDB:
    arguments:
      $apiToken: "%tmdb.api-token%"
      $defaultMovieLanguage: "%tmdb.movies.language%"
      $defaultShowLanguage: "%tmdb.shows.language%"
  tracky\dataprovider\TVDB:
    arguments:
      $baseUrl: "https://api4.thetvdb.com/v4/"
      $apiKey: "%tvdb.api-key%"
      $authTokenFilePath: "%kernel.cache_dir%/tvdb-api-token"
      $maxAuthTokenAge: 604800
      $defaultMovieLanguage: "%tvdb.movies.language%"
      $defaultShowLanguage: "%tvdb.shows.language%"
  tracky\ImageFetcher:
    arguments:
      $storagePath: "%image-fetcher.storage-path%"
  tracky\scrobbler\Scrobbler:
    arguments:
      $useQueue: "%scrobbler.use-queue%"
  tracky\Config:
    arguments:
      $container: "@service_container"